name: Doas
version: '${project.version}'
main: com.github.arcoda.doas.Doas
authors: [ Arcoda ]
description: Talk or execute a command as another player
api-version: 1.13
commands:
  doas:
    description: Talk or execute a command as another player
  doas-admin:
    description: Console-only commands
    usage: doas-admin [add/remove] [player] & doas-admin reload
permissions:
  doas.talk:
    description: Allows to talk as another player
    default: false
  doas.command:
    description: Allows to send a command as another player
    default: false
  doas.allplayer:
    description: Allows to both talk&send command as another player
    default: false
    children:
      doas.talk: true
      doas.command: true
  doas.console:
    description: Allow to execute a command as console
    default: false
  doas.*:
    description: Wildcard to get all permissions
    default: false
    children:
      doas.allplayer: true
      doas.console: true